### ISSUE TITLE
UART communication between CC1312 and ESP32

### ISSUE THREAD

**Issue by luisan00** [btcven/radio-firmware#35]
## Communicating MCUs through the UART port
This feature is necessary to communicate both MCUs

### We have a bunch of options available, for example:
* **SLIP** *- Serial Line Internet Protocol -*
  - https://tools.ietf.org/html/rfc1055

* **CSLIP** *- Compressed SLIP -*
  - https://tools.ietf.org/html/rfc1144

* **KISS** *- keep it simple, stupid -*
  - https://en.wikipedia.org/wiki/KISS_(TNC)

* Modbus RTU
  - https://www.rtautomation.com/technologies/modbus-rtu/
  - https://ipc2u.com/articles/knowledge-base/modbus-rtu-made-simple-with-detailed-descriptions-and-examples

**Comment by luisan00** [comment]
PR #83 add  a communication layer
also V.A.I.N.A adds with the PR #93  a basic functionality for to use IPV6 addresses

**Comment by jeandudey** [comment]
SLIP and VAINA are merged, so it's fine to close this, the radio and the esp32 talk to each other nicely right now :)
