### ISSUE TITLE
capture packets in the network layer, to be processed inside AODVv2 module

### ISSUE THREAD

**Issue by gustavosinbandera1** [btcven/radio-firmware#36]
## This feature is required to process the packages within the GNRC_AODVV2 module.
when the application layer tries to send a message, it is necessary to capture the packet in the network layer, in order to process and find routes 

**Describe the solution you'd like**

Each layer of the network stack runs in its own thread and each lower layer thread has a higher priority than any upper layer thread. In this regard, the thread of the MAC layer implementation has the highest priority and threads on the application layer have the lowest priority. The communication between threads is handled by the kernel's @ref core_msg functionality and by the @ref net_gnrc_netapi. Most of the times IPC will take place between threads of neighboring layers for packets that traverse the network stack up or down.

Due to the design of @ref net_gnrc "GNRC" and the nature of inter-process communication, it is crucial for a new module that introduces a new thread to follow a certain programming construct if it desires to interact with other threads without blocking the system: Utilizing an `event loop`.
Hence, a thread for @ref net_gnrc "GNRC" will usually consist of four basic steps.

1. Initialize a message queue (note that its size **must** be a power of twosee @ref msg_init_queue())
2. register for a @ref net_gnrc_nettype
3. wait for a message
4. react appropriately to a message and return to 3.

to capture packets that go to the ipv6 module we must subscribe to network messages through the IPC (intercommunication process), which allows to capture messages from some thread (app layer for this case).
1. To be able to listen incoming packets in UDP module we need to create a thread to handle _event_loop
```cpp
if (_pid == KERNEL_PID_UNDEF) {
    /* start thread */
    _pid = thread_create(_stack, sizeof(_stack), GNRC_UDP_PRIO,
                         THREAD_CREATE_STACKTEST, _event_loop, NULL, "IPV6");
  }
```
2.subscribe to specific messages
```cpp
 void *_event_loop(void *arg)
 {
  static msg_t _msg_q[Q_SZ];
  (void)arg;
   msg_init_queue(_msg_q, Q_SZ);
   gnrc_netreg_entry me_reg = GNRC_NETREG_ENTRY_INIT_PID(
   GNRC_NETREG_DEMUX_CTX_ALL,
   sched_active_pid);
  gnrc_netreg_register(GNRC_NETTYPE_UDP, &me_reg);
  while (1) {
         msg_receive(&msg);
         switch (msg.type) {
             case TYPE1:
                 callback1();
                  break;
             case TYPE2:
                  callback2();
                  break;

              ...
          }
      }
      return NULL;
  }
```

To have the AODVv2 module waiting for incoming and outgoing UDP packets, we need to use something like this:
```cpp
static void *_event_loop(void *args)
{

    msg_t msg, reply, msg_q[CONFIG_GNRC_UDP_MSG_QUEUE_SIZE];
    gnrc_netreg_entry_t me_reg = GNRC_NETREG_ENTRY_INIT_PID(GNRC_NETREG_DEMUX_CTX_ALL,
                                                            sched_active_pid);

    (void)args;
    msg_init_queue(msg_q, CONFIG_GNRC_UDP_MSG_QUEUE_SIZE);

    /* start event loop */
    while (1) {
    msg_receive(&msg);
    switch (msg.type) {
    case GNRC_NETAPI_MSG_TYPE_RCV:
      _receive(msg.content.ptr);
      break;
    case GNRC_NETAPI_MSG_TYPE_SND:
      DEBUG("*****AODV**** CAPTURING MESSAGE FROM APPLICATION");
      gnrc_process_message(msg.content.ptr); //to capture the headers and edit some of them
      break;
    case GNRC_NETAPI_MSG_TYPE_SET:
    case GNRC_NETAPI_MSG_TYPE_GET:
      msg_reply(&msg, &reply);
      break;
    default:
      DEBUG("udp: received unidentified message\n");
      break;
    }
  }

    return NULL;
}
```
To be able to test the **GNRC_AODVV2_MODULE**, was needed to remove the auto init functionality  for UDP protocol, in order to handle the packet directly in gnrc_aodvv2 module

edit the file **sys/auto_init/auto_init.c

```cpp
#ifdef MODULE_GNRC_UDP
    //DEBUG("Auto init UDP module.\n");
    //gnrc_udp_init();
#endif
```
it could be great to be able to capture incoming packets to ipv6 module, but in my begin was not possible to get the packet inside gnrc_aodvv2 module first than the ipv6 module itself

**Comment by jeandudey** [comment]
This is already implemented, and moved to Done correctly.
